const seedData = {
  page: 'Dashboard',
  loggedIn: localStorage.getItem('assetflow-auth') === 'true',
  assets: [
    {tag:'AF-0012',name:'Dell Latitude 7440',cat:'Electronics',status:'Allocated',holder:'Priya Shah',dept:'Engineering',location:'Bengaluru HQ',condition:'Excellent',returnDate:'2026-07-20'},
    {tag:'AF-0062',name:'Epson Projector',cat:'Electronics',status:'Under Maintenance',holder:'',dept:'Facilities',location:'HQ Floor 2',condition:'Needs repair'},
    {tag:'AF-0201',name:'Ergo Office Chair',cat:'Furniture',status:'Available',holder:'',dept:'Operations',location:'Warehouse',condition:'Good'},
    {tag:'AF-0087',name:'Toyota Forklift',cat:'Vehicles',status:'Available',holder:'',dept:'Field Ops',location:'Warehouse',condition:'Good'},
    {tag:'AF-0301',name:'Sony A7 Camera',cat:'Electronics',status:'Reserved',holder:'Marketing',dept:'Marketing',location:'Studio',condition:'Good'}
  ],
  departments:[['Engineering','Aditi Rao','—','Active'],['Facilities','Rohan Mehta','—','Active'],['Field Ops (East)','Sana Iqbal','Field Ops','Inactive']],
  bookings:[{resource:'Conference Room B2',start:'09:00',end:'10:00',time:'09:00 – 10:00',team:'Procurement Team',status:'Ongoing'}],
  notices:[['💻','Laptop AF-0014 assigned to Priya Shah','Allocation completed successfully','2m ago'],['🔧','Maintenance request AF-0055 approved','Projector repair is ready for technician assignment','18m ago'],['📅','Booking confirmed: Room B2','Your booking is scheduled for 2:00 – 3:00 PM','1h ago'],['↗','Transfer approved: AF-0033','Asset transferred to Facilities Department','3h ago'],['⚠','Overdue return: AF-0021','This laptop was due back 3 days ago','1d ago'],['✓','Audit discrepancy flagged','AF-0088 marked as damaged during Q3 audit','2d ago']]
};
const STORE_KEY = 'assetflow-live-data-v1';
const storedData = JSON.parse(localStorage.getItem(STORE_KEY) || 'null');
const state = {
  ...seedData,
  ...(storedData || {}),
  page: 'Dashboard',
  loggedIn: localStorage.getItem('assetflow-auth') === 'true'
};
const liveChannel = 'BroadcastChannel' in window ? new BroadcastChannel('assetflow-live-sync') : null;
function persistData() {
  localStorage.setItem(STORE_KEY, JSON.stringify({assets:state.assets, departments:state.departments, bookings:state.bookings, notices:state.notices}));
  liveChannel?.postMessage({type:'state-updated'});
}
function syncData() {
  const fresh = JSON.parse(localStorage.getItem(STORE_KEY) || 'null');
  if (!fresh) return;
  Object.assign(state, fresh);
  if (state.loggedIn) render();
}
liveChannel?.addEventListener('message', syncData);
window.addEventListener('storage', event => { if (event.key === STORE_KEY) syncData(); });
const nav = [['Dashboard','⌂'],['Organization setup','▦'],['Assets','▣'],['Allocation & Transfer','⇄'],['Resource Booking','▤'],['Maintenance','⌕'],['Audit','✓'],['Reports','◔'],['Notifications','♧']];
const $ = s => document.querySelector(s);
const badge = s => `<span class="badge ${s.toLowerCase().replaceAll(' ','-')}">${s}</span>`;
const assetRows = () => state.assets.map(a=>`<tr><td><b>${a.tag}</b></td><td class="asset-name">${a.name}<span>${a.condition}</span></td><td>${a.cat}</td><td>${badge(a.status)}</td><td>${a.holder || '—'}</td><td>${a.location}</td><td><button class="ghost" onclick="openAsset('${a.tag}')">View</button></td></tr>`).join('');
function shell(content,title=state.page,sub='Keep your assets, resources and teams moving in sync.') { return `<div class="shell"><aside class="sidebar"><div class="brand"><span class="brand-mark">A</span><span>AssetFlow</span></div><nav class="nav-group">${nav.map(([p,i])=>`<button class="nav-item ${state.page===p?'active':''}" onclick="go('${p}')"><span class="nav-ico">${i}</span><span>${p}</span></button>`).join('')}</nav><div class="profile"><div class="avatar">AS</div><div><b>Alex Sharma</b><span>Asset Manager</span></div></div></aside><main class="main"><div class="topbar"><div><div class="eyebrow">AssetFlow / ${title}</div><h1>${title}</h1><p class="sub">${sub}</p></div><div class="top-actions"><button class="bell" onclick="go('Notifications')">♧<i></i></button><button class="primary" onclick="quickAction()">＋ Quick action</button></div></div>${content}</main></div>`; }
function dashboard(){const available=state.assets.filter(a=>a.status==='Available').length,allocated=state.assets.filter(a=>a.status==='Allocated').length,maintenance=state.assets.filter(a=>a.status==='Under Maintenance').length,overdue=state.assets.filter(a=>a.returnDate&&new Date(a.returnDate)<new Date()).length;const k=[['▣','Assets available',available,'Live inventory count'],['◈','Assets allocated',allocated,'Currently assigned'],['🔧','In maintenance',maintenance,'Status updates instantly'],['▤','Active bookings',state.bookings.length,'Synced across tabs'],['⇄','Pending transfers',state.notices.filter(n=>n[1].includes('Transfer request')).length,'Needs your review'],['↳','Overdue returns',overdue,overdue?'Follow up required':'All returns on track']];return shell(`<div class="kpis">${k.map(x=>`<div class="card kpi"><div class="kpi-head"><span>${x[1]}</span><span class="kpi-icon">${x[0]}</span></div><strong>${x[2]}</strong><small>${x[3]}</small></div>`).join('')}</div><div class="quick-actions"><button class="primary" onclick="go('Assets')">＋ Register asset</button><button class="secondary" onclick="go('Resource Booking')">Book resource</button><button class="secondary" onclick="go('Maintenance')">Raise request</button></div><div class="grid-2"><section class="card section"><div class="section-head"><h2>Today’s operational view</h2><a onclick="go('Reports')">View reports →</a></div><div class="overdue"><div class="alert-icon">⚠</div><div><strong>${overdue} assets overdue for return</strong><p>${overdue?'These assignments need a follow-up today.':'No overdue returns right now.'}</p></div></div>${state.notices.slice(0,3).map(n=>`<div class="activity"><div class="activity-icon">${n[0]}</div><div><b>${n[1]}</b><span>${n[2]} · ${n[3]}</span></div></div>`).join('')}</section><section class="card section"><div class="section-head"><h2>Live activity</h2><a onclick="go('Notifications')">All notifications →</a></div><div class="timeline"><div class="timeline-item"><b>${state.assets.length} assets in the directory</b><p>Changes are persisted to your local workspace.</p></div><div class="timeline-item"><b>${state.bookings.length} shared-resource bookings</b><p>Overlap checks run before every reservation.</p></div><div class="timeline-item"><b>Last update: just now</b><p>Open this app in another tab to see live sync.</p></div></div></section></div>`,'Dashboard','Live operational data from your AssetFlow workspace.');}
function org(){return shell(`<div class="card section"><div class="tabs"><button class="tab active">Departments</button><button class="tab">Asset categories</button><button class="tab">Employee directory</button></div><div class="toolbar"><div class="search"><input placeholder="Search departments" /></div><button class="primary" onclick="showDepartment()">＋ Add department</button></div><div class="table-card"><table class="data-table"><thead><tr><th>Department</th><th>Department head</th><th>Parent department</th><th>Status</th><th></th></tr></thead><tbody>${state.departments.map(d=>`<tr><td class="asset-name">${d[0]}</td><td>${d[1]}</td><td>${d[2]}</td><td>${badge(d[3])}</td><td><button class="ghost">Edit</button></td></tr>`).join('')}</tbody></table></div><div class="empty-note">Changes here automatically update department options in registration and allocation workflows.</div></div>`,'Organization setup','Admin-only master data for departments, categories and employees.');}
function assets(){return shell(`<div class="toolbar"><div class="search"><input id="assetSearch" oninput="filterAssets()" placeholder="Search by tag, serial number or QR code" /></div><div class="filters"><select><option>All categories</option><option>Electronics</option><option>Furniture</option></select><select><option>All statuses</option><option>Available</option><option>Allocated</option></select><button class="primary" onclick="showAssetForm()">＋ Register asset</button></div></div><div class="card table-card"><table class="data-table"><thead><tr><th>Asset tag</th><th>Name</th><th>Category</th><th>Status</th><th>Assigned to</th><th>Location</th><th></th></tr></thead><tbody id="assetRows">${assetRows()}</tbody></table></div>`,'Assets','Register, find and track every asset through its lifecycle.');}
function allocation(){return shell(`<div class="allocation"><div><section class="asset-summary"><div class="label">SELECTED ASSET</div><h2>AF-0012 · Dell Latitude 7440</h2><span class="status">Currently allocated</span><p class="sub" style="color:#d6d8ff">Electronics · Serial: DL-7482-A9 · Bengaluru HQ</p></section><section class="card section"><div class="conflict"><b>Already allocated to Priya Shah (Engineering)</b>Direct re-allocation is blocked. Submit a transfer request instead.</div><h2 style="margin-bottom:16px">Transfer request</h2><div class="form-grid"><div class="field"><label>From</label><input value="Priya Shah" disabled></div><div class="field"><label>To</label><select><option>Select employee…</option><option>Raj Mehta</option><option>Sana Iqbal</option></select></div><div class="field full"><label>Reason</label><textarea placeholder="Why should this asset be transferred?"></textarea></div></div><button class="primary" style="margin-top:16px" onclick="submitTransfer()">Submit transfer request</button></section></div><section class="card section"><div class="section-head"><h2>Allocation history</h2>${badge('Allocated')}</div><div class="timeline"><div class="timeline-item"><b>Mar 12 · Allocated to Priya Shah</b><p>Engineering · Expected return Jul 20</p></div><div class="timeline-item"><b>Jan 04 · Returned by Arjun Nair</b><p>Condition check-in: Good</p></div><div class="timeline-item"><b>Sep 18 · Registered by Alex Sharma</b><p>Initial status: Available</p></div></div></section></div>`,'Allocation & Transfer','Safely allocate assets and manage transfers without double-allocation.');}
function booking(){const blocks=state.bookings.map(b=>`<div class="slot"><div class="time">${b.start}</div><div class="booking-block">Booked · ${b.team} · ${b.time}</div></div>`).join('');return shell(`<div class="booking-layout"><section class="card calendar"><div class="date-row"><div><div class="eyebrow">Shared resource</div><h2>Conference Room B2 · Live schedule</h2></div><button class="ghost">Today</button></div><div class="slots">${blocks}<div class="slot"><div class="time">Available</div><div></div></div></div></section><section class="card section"><h2>Book a slot</h2><p class="sub">A resource can only have one active booking per time slot.</p><div class="form-grid" style="margin-top:17px"><div class="field full"><label>Resource</label><select><option>Conference Room B2</option><option>Projector AF-0062</option><option>Company Van AF-0343</option></select></div><div class="field"><label>Start time</label><input id="start" type="time" value="09:30" required></div><div class="field"><label>End time</label><input id="end" type="time" value="10:30" required></div><div class="field full"><label>Purpose</label><input id="bookingPurpose" placeholder="e.g. Team planning" maxlength="120" required></div></div><button class="primary" style="margin-top:16px" onclick="bookSlot()">Confirm booking</button></section></div>`,'Resource Booking','Reserve shared resources with clear availability and overlap protection.');}
function maintenance(){const cols=[['Pending',[['AF-0062','Projector bulb not turning on','High']]],['Approved',[['AF-003','AC unit noisy compressor','Medium']]],['Technician assigned',[['AF-0078','Forklift · Tech: R. Varma','High']]],['In progress',[['AF-0897','Printer jam · parts ordered','Medium']]],['Resolved',[['AF-0873','Chair repair · resolved 7 Jul','Low']]]];return shell(`<div class="toolbar"><p class="sub">Approve requests before work begins. Resolving returns the asset to Available.</p><button class="primary" onclick="showMaintenance()">＋ Raise request</button></div><div class="kanban">${cols.map((c,i)=>`<div class="kanban-col"><h3>${c[0]} <span>${c[1].length}</span></h3>${c[1].map(r=>`<div class="card request"><b>${r[0]}</b><p>${r[1]}</p>${badge(r[2])}${i<4?` <button class="ghost" style="float:right;padding:4px 7px" onclick="advanceRequest('${r[0]}')">Move →</button>`:''}</div>`).join('')}</div>`).join('')}</div><div class="empty-note">Approving a request changes the asset status to Under Maintenance; resolving it returns the asset to Available and preserves the full history.</div>`,'Maintenance','A structured approval workflow for every repair and servicing request.');}
function audit(){return shell(`<section class="card"><div class="audit-head"><div class="audit-icon">✓</div><div><b>Q3 audit: Engineering department</b><span>1–15 July · Auditors: Aditi Rao, Sana Iqbal</span></div><button class="ghost" style="margin-left:auto">Manage auditors</button></div><div class="table-card"><table class="data-table"><thead><tr><th>Asset</th><th>Expected location</th><th>Assigned holder</th><th>Verification</th><th></th></tr></thead><tbody><tr><td class="asset-name">AF-003 · Dell laptop</td><td>Desk E12</td><td>Priya Shah</td><td>${badge('Verified')}</td><td>✓</td></tr><tr><td class="asset-name">AF-9921 · Office chair</td><td>Desk E14</td><td>Arjun Nair</td><td>${badge('Lost')}</td><td><button class="ghost">Review</button></td></tr><tr><td class="asset-name">AF-9838 · Monitor</td><td>Desk E15</td><td>—</td><td>${badge('Maintenance')}</td><td><button class="ghost">Review</button></td></tr></tbody></table></div><div class="section"><div class="overdue"><div class="alert-icon">⚠</div><div><strong>2 assets flagged · discrepancy report generated</strong><p>Review missing and damaged items before closing this audit cycle.</p></div><button class="primary" onclick="closeAudit()">Close audit cycle</button></div></section>`,'Asset Audit','Verify inventory, identify discrepancies and retain a locked audit trail.');}
function reports(){return shell(`<div class="report-grid"><section class="card section"><div class="section-head"><h2>Utilization by department</h2><select><option>Last 6 months</option></select></div><div class="chart">${[42,66,52,79,63,88].map((n,i)=>`<div class="bar" style="height:${n}%"><i>${['Jan','Feb','Mar','Apr','May','Jun'][i]}</i></div>`).join('')}</div></section><section class="card section"><div class="section-head"><h2>Maintenance frequency</h2><a>View details →</a></div><div class="insight"><b>Electronics</b><p>18 service requests · 34% of all maintenance</p></div><div class="insight"><b>Vehicles</b><p>8 service requests · Average resolution: 2.3 days</p></div><div class="insight"><b>Furniture</b><p>5 service requests · Lowest incident rate</p></div></section></div><div class="grid-2" style="margin-top:18px"><section class="card section"><h2>Most-used assets</h2><div class="insight"><b>Room B2</b><p>34 bookings this month</p></div><div class="insight"><b>Van AF-0343</b><p>21 trips this month</p></div><div class="insight"><b>Projector AF-0335</b><p>18 uses this month</p></div></section><section class="card section"><h2>Attention needed</h2><div class="insight"><b>Forklift AF-0087</b><p>Service due in 5 days</p></div><div class="insight"><b>Laptop AF-0020</b><p>4 years old · nearing retirement</p></div><div style="margin-top:14px"><button class="primary" onclick="downloadReport()">⇩ Export report</button></div></section></div>`,'Reports & Analytics','Operational insights for utilization, maintenance and resource planning.');}
function notifications(){return shell(`<section class="card"><div class="tabs"><button class="tab active">All</button><button class="tab">Alerts</button><button class="tab">Approvals</button><button class="tab">Bookings</button></div>${state.notices.map((n,i)=>`<div class="notification ${i<3?'unread':''}"><div class="nicon">${n[0]}</div><div><b>${n[1]}</b><p>${n[2]}</p></div><time>${n[3]}</time></div>`).join('')}</section>`,'Activity logs & Notifications','Stay up to date on approvals, bookings, returns and audit activity.');}
const pages={'Dashboard':dashboard,'Organization setup':org,'Assets':assets,'Allocation & Transfer':allocation,'Resource Booking':booking,'Maintenance':maintenance,'Audit':audit,'Reports':reports,'Notifications':notifications};
function render(){document.title=`AssetFlow | ${state.page}`; $('#app').innerHTML=state.loggedIn?pages[state.page]():login();}
function go(p){state.page=p;render();window.scrollTo(0,0)}
function login(){return `<div class="login"><section class="login-art"><div class="brand"><span class="brand-mark">A</span>AssetFlow</div><h1>Keep every asset in motion.</h1><p>A calm, connected workspace for your physical assets, shared resources and operational teams.</p></section><section class="login-form"><div class="brand" style="color:var(--ink);padding:0"><span class="brand-mark">A</span>AssetFlow</div><h2>Welcome back</h2><p class="sub">Sign in to your organization workspace.</p><div class="field"><label>WORK EMAIL</label><input type="email" value="alex@assetflow.io"></div><div class="field" style="margin-top:14px"><label>PASSWORD</label><input type="password" value="password"></div><div style="text-align:right;margin-top:9px"><a style="font-size:12px;color:var(--primary);font-weight:700">Forgot password?</a></div><button class="primary" onclick="signIn()">Sign in to AssetFlow</button><p class="login-note">New here? <a style="color:var(--primary);font-weight:700">Create an employee account</a><br><br>Admin roles are assigned later by your organization.</p></section></div>`}
function signIn(){state.loggedIn=true;localStorage.setItem('assetflow-auth','true');render();toast('Welcome back, Alex.')}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function modal(title,body,action='Save',fn='closeModal()'){document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="modal"><div class="modal"><h2>${title}</h2>${body}<div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="${fn}">${action}</button></div></div></div>`)}function closeModal(){$('#modal')?.remove()}
function showAssetForm(){modal('Register new asset',`<div class="form-grid"><div class="field"><label>Asset name</label><input id="newName" placeholder="e.g. Lenovo ThinkPad"></div><div class="field"><label>Category</label><select id="newCat"><option>Electronics</option><option>Furniture</option><option>Vehicles</option></select></div><div class="field"><label>Location</label><input id="newLocation" placeholder="e.g. Bengaluru HQ"></div><div class="field"><label>Condition</label><select id="newCondition"><option>Good</option><option>Excellent</option><option>Fair</option></select></div></div>`,'Register asset','registerAsset()')}
function registerAsset(){const n=$('#newName').value.trim(),location=$('#newLocation').value.trim();if(n.length<3||n.length>80)return toast('Asset name must be between 3 and 80 characters.');if(!/^[\p{L}\p{N} .()/-]+$/u.test(n))return toast('Asset name contains unsupported characters.');if(!location||location.length<2||location.length>80||!/^[\p{L}\p{N} .()/-]+$/u.test(location))return toast('Enter a valid asset location (2–80 characters).');if(state.assets.some(a=>a.name.toLowerCase()===n.toLowerCase()))return toast('An asset with this name already exists.');const nextTag=`AF-${String(Math.max(0,...state.assets.map(a=>Number(a.tag.slice(3))||0))+1).padStart(4,'0')}`;state.assets.unshift({tag:nextTag,name:n,cat:$('#newCat').value,status:'Available',holder:'',dept:'',location,condition:$('#newCondition').value});persistData();closeModal();render();toast(`${n} registered and available for allocation.`)}
function showDepartment(){modal('Create department',`<div class="form-grid"><div class="field"><label>Department name</label><input id="deptName" placeholder="e.g. Marketing"></div><div class="field"><label>Department head</label><input id="deptHead" placeholder="Select employee"></div></div>`,'Create department','createDepartment()')}
function createDepartment(){const n=$('#deptName').value.trim(),head=$('#deptHead').value.trim();if(n.length<2||n.length>60)return toast('Department name must be between 2 and 60 characters.');if(!/^[\p{L}\p{N} &()-]+$/u.test(n))return toast('Department name contains unsupported characters.');if(state.departments.some(d=>d[0].toLowerCase()===n.toLowerCase()))return toast('That department already exists.');state.departments.push([n,head||'Unassigned','—','Active']);persistData();closeModal();render();toast('Department created successfully.')}
function submitTransfer(){const reason=document.querySelector('textarea[placeholder="Why should this asset be transferred?"]')?.value.trim();if(!reason||reason.length<10||reason.length>300)return toast('Provide a transfer reason between 10 and 300 characters.');state.notices.unshift(['↗','Transfer request submitted','AF-0012 transfer awaits manager approval','Now']);persistData();render();toast('Transfer request submitted for approval.');}
function bookSlot(){const s=$('#start').value,e=$('#end').value,purpose=$('#bookingPurpose')?.value.trim();if(!s||!e||s>=e)return toast('End time must be later than start time.');if(!purpose||purpose.length<3||purpose.length>120)return toast('Purpose must be between 3 and 120 characters.');const overlaps=state.bookings.some(b=>b.resource==='Conference Room B2'&&s<b.end&&e>b.start);if(overlaps)return toast('That time overlaps an existing booking.');state.bookings.push({resource:'Conference Room B2',start:s,end:e,time:`${s} – ${e}`,team:'Alex Sharma',status:'Upcoming',purpose});state.notices.unshift(['📅','Booking confirmed: Conference Room B2',`Your booking is scheduled for ${s} – ${e}`,'Now']);persistData();render();toast('Booking confirmed. A reminder has been scheduled.');}
function showMaintenance(){modal('Raise maintenance request',`<div class="form-grid"><div class="field full"><label>Asset</label><select><option>AF-0012 · Dell Latitude 7440</option><option>AF-0087 · Toyota Forklift</option></select></div><div class="field"><label>Priority</label><select><option>Medium</option><option>High</option><option>Low</option></select></div><div class="field full"><label>Issue description</label><textarea id="maintenanceIssue" placeholder="Describe the issue" minlength="10" maxlength="500" required></textarea></div></div>`,'Submit request','submitMaintenance()')}
function submitMaintenance(){const issue=$('#maintenanceIssue')?.value.trim();if(!issue||issue.length<10||issue.length>500)return toast('Describe the issue in 10–500 characters.');closeModal();state.notices.unshift(['🔧','Maintenance request submitted','Awaiting Asset Manager approval','Now']);persistData();render();toast('Maintenance request submitted for approval.');}
function advanceRequest(id){toast(`${id} moved to the next maintenance stage.`)}function closeAudit(){toast('Audit cycle closed. Discrepancy report is ready.')}
function filterAssets(){let q=$('#assetSearch').value.toLowerCase();$('#assetRows').innerHTML=state.assets.filter(a=>Object.values(a).join(' ').toLowerCase().includes(q)).map(a=>`<tr><td><b>${a.tag}</b></td><td class="asset-name">${a.name}<span>${a.condition}</span></td><td>${a.cat}</td><td>${badge(a.status)}</td><td>${a.holder||'—'}</td><td>${a.location}</td><td><button class="ghost" onclick="openAsset('${a.tag}')">View</button></td></tr>`).join('')}
function openAsset(tag){let a=state.assets.find(x=>x.tag===tag);modal(`${a.tag} · ${a.name}`,`<div class="form-grid"><div class="field"><label>Status</label><input value="${a.status}" disabled></div><div class="field"><label>Condition</label><input value="${a.condition}" disabled></div><div class="field"><label>Holder</label><input value="${a.holder||'Unassigned'}" disabled></div><div class="field"><label>Location</label><input value="${a.location}" disabled></div></div><div class="empty-note">Asset history is retained for allocations, returns and maintenance events.</div>`,'Close','closeModal()')}
function quickAction(){showAssetForm()}function downloadReport(){const b=new Blob(['AssetFlow Operational Report\nGenerated: '+new Date().toLocaleString()+'\n\nAssets available: 128\nAssets allocated: 76\nActive bookings: 9'],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='assetflow-operational-report.txt';a.click();URL.revokeObjectURL(a.href);toast('Operational report exported.')}
render();
